Vagrant.configure("2") do |config|
  # Base box settings
  config.vm.box = "gutehall/ubuntu24-04"
  config.vm.box_version = "2025.02.20"

  # Shared folder between host and guest VMs
  config.vm.synced_folder "./shared", "/vagrant_shared"

  # Control-plane (server) node
  config.vm.define "eholzerS" do |server|
    server.vm.hostname = "eholzerS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider :vmware_desktop do |v|
      v.vmx["numvcpus"] = "1"
      v.vmx["memsize"] = "512"
    end

    # Install K3s server and export node token
    server.vm.provision "shell", privileged: true, path: "provisioning_scripts/server_provision.sh"
  end

  # Worker node
  config.vm.define "eholzerSW" do |worker|
    worker.vm.hostname = "eholzerSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider :vmware_desktop do |v|
      v.vmx["numvcpus"] = "1"
      v.vmx["memsize"] = "512"
    end

    # Wait for token file and install K3s agent
    worker.vm.provision "shell", privileged: true, path: "provisioning_scripts/worker_provision.sh"
  end
end
