Vagrant.configure("2") do |config|
    config.vm.box = "gutehall/ubuntu24-04"
    config.vm.box_version = "2025.02.20"
  
    config.vm.hostname = "eholzerS"
    config.vm.network "private_network", ip: "192.168.56.110"
  
    config.vm.provider "vmware_desktop" do |v|
      v.vmx["numvcpus"] = "2"
      v.vmx["memsize"] = "2048"
    end
  
    config.vm.provision "shell", path: "provisioning_scripts/server_provision.sh"
  end
  